# for local development
version: '3.7'
services:
  quasar:
    build:
      context: ./app/myproject
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - './app/myproject:/app'
    command: /bin/sh -c "yarn && quasar dev"